.PHONY: clean All

All:
	@echo "----------Building project:[ rs232 - Debug ]----------"
	@cd "rs232" && "$(MAKE)" -f  "rs232.mk"
clean:
	@echo "----------Cleaning project:[ rs232 - Debug ]----------"
	@cd "rs232" && "$(MAKE)" -f  "rs232.mk" clean
